export const productData = [
  {
    id: 1,
    title: "shirt",
    description: "sdlsdasld/sjdhas",
    price: 123,
    brand: "Nike",
    stock: 38,
  },
  {
    id: 2,
    title: "shirt",
    description: "sdlsdasld/sjdhas",
    price: 883,
    brand: "Nike",
    stock: 27,
  },
  {
    id: 3,
    title: "shirt",
    description: "sdlsdasld/sjdhas",
    price: 563,
    brand: "Nike",
    stock: 178,
  },
  {
    id: 4,
    title: "shirt",
    description: "sdlsdasld/sjdhas",
    price: 345,
    brand: "Nike",
    stock: 76,
  },
  {
    id: 5,
    title: "shirt",
    description: "sdlsdasld/sjdhas",
    price: 210,
    brand: "Nike",
    stock: 97,
  },
];
