export const staffMockData = [
  {
    id: 1,
    name: "Kate",
    surname: "Jhonson",
    gender: "female",
    email: "kate@gmail.com",
    number: 364646464,
    role: "sales-manager",
  },
  {
    id: 2,
    name: "Jane",
    surname: "Arthur",
    gender: "female",
    email: "jane@gmail.com",
    number: 833930308,
    role: "seller",
  },
  {
    id: 3,
    name: "David",
    surname: "Thomas",
    gender: "male",
    email: "david@gmail.com",
    number: 473839303,
    role: "seller",
  },
  {
    id: 4,
    name: "Robert",
    surname: "Jackson",
    gender: "male",
    email: "robert@gmail.com",
    number: 273738849,
    role: "sales-manager",
  },
  {
    id: 5,
    name: "Tom",
    surname: "Thomas",
    gender: "male",
    email: "tom@gmail.com",
    number: 463637390,
    role: "seller",
  },
  {
    id: 6,
    name: "Robert",
    surname: "Philip",
    gender: "male",
    email: "robert@gmail.com",
    number: 475757577,
    role: "cashier",
  },
  {
    id: 7,
    name: "Anna",
    surname: "Jhonson",
    gender: "female",
    email: "anna@gmail.com",
    number: 475757577,
    role: "cashier",
  },
];
